export const UI_CONSTANTS = {
  SEARCH_DEBOUNCE_DELAY: 500,
  LOADING_TEXT: '로딩 중...',
  NO_RESULTS_TEXT: '검색 결과가 없습니다.',
  LOADING_TOP_RATED_TEXT: '평점 높은 영화 목록을 불러오는 중입니다...',
  SEARCH_PLACEHOLDER: '영화 제목을 입력하세요...',
  HERO_TITLE: '오늘 볼 영화를 찾아보세요',
  HERO_DESCRIPTION: '제목으로 검색해서 원하는 영화를 찾고, 마음에 드는 작품은 하트로 즐겨찾기에 저장할 수 있습니다.',
  FAVORITES_TITLE: '즐겨찾기',
  EMPTY_FAVORITES_TEXT: '즐겨찾기한 영화가 없습니다.',
  LOGIN_TITLE: '로그인',
  REGISTER_TITLE: '회원가입',
  VERIFY_EMAIL_TITLE: '이메일 인증',
  VERIFY_EMAIL_LOADING_TEXT: '이메일을 인증하는 중...',
  VERIFY_EMAIL_SUCCESS_TEXT: '이메일 인증이 완료되었습니다! 이제 로그인할 수 있습니다.',
  VERIFY_EMAIL_SUCCESS_BUTTON: '로그인 페이지로 이동',
  LOGOUT_BUTTON: '로그아웃',
  FAVORITES_BUTTON: '즐겨찾기',
  BACK_BUTTON: '뒤로 가기',
  SUBMIT_BUTTON: '제출',
  LOGIN_BUTTON: '로그인',
  REGISTER_BUTTON: '회원가입',
  RESEND_VERIFICATION_BUTTON: '인증 이메일 재전송',
  FORGOT_PASSWORD_BUTTON: '비밀번호 찾기',
  RESET_PASSWORD_BUTTON: '비밀번호 재설정',
  EMAIL_LABEL: '이메일',
  PASSWORD_LABEL: '비밀번호',
  NAME_LABEL: '이름',
  CONFIRM_PASSWORD_LABEL: '비밀번호 확인',
  TOKEN_LABEL: '토큰',
  PLOT_LABEL: '줄거리',
  DIRECTOR_LABEL: '감독',
  ACTORS_LABEL: '출연',
  GENRE_LABEL: '장르',
  RATING_LABEL: '평점',
  NO_PLOT_TEXT: '줄거리 정보가 없습니다.',
  NO_INFO_TEXT: '정보 없음',
  NO_RATING_TEXT: '평점 없음',
  EMAIL_PLACEHOLDER: 'your@email.com',
  PASSWORD_PLACEHOLDER: '비밀번호를 입력하세요',
  NAME_PLACEHOLDER: '이름을 입력하세요',
  PASSWORD_MIN_LENGTH_PLACEHOLDER: '비밀번호를 입력하세요 (최소 6자)',
  EMAIL_ALREADY_EXISTS_ERROR: '이미 등록된 이메일입니다.',
  INVALID_CREDENTIALS_ERROR: '이메일 또는 비밀번호가 올바르지 않습니다.',
  EMAIL_VERIFICATION_REQUIRED_ERROR: '이메일 인증이 필요합니다.',
  USER_NOT_FOUND_ERROR: '사용자를 찾을 수 없습니다.',
  RESOURCE_NOT_FOUND_ERROR: '요청한 리소스를 찾을 수 없습니다.',
  INVALID_TOKEN_ERROR: '유효하지 않은 인증 토큰입니다.',
  EXPIRED_TOKEN_ERROR: '유효하지 않거나 만료된 토큰입니다.',
  ALREADY_VERIFIED_ERROR: '이미 인증된 이메일입니다.',
  MOVIE_NOT_FOUND_ERROR: '영화를 찾을 수 없습니다.',
  ALREADY_FAVORITED_ERROR: '이미 즐겨찾기에 추가된 영화입니다.',
  FAVORITE_NOT_FOUND_ERROR: '즐겨찾기를 찾을 수 없습니다.',
  FAVORITE_PROCESS_ERROR: '즐겨찾기 처리 중 오류가 발생했습니다.',
  SEARCH_ERROR: '영화를 불러오는 중 오류가 발생했습니다.',
  NETWORK_ERROR: '네트워크 연결을 확인해주세요.',
  TIMEOUT_ERROR: '요청 시간이 초과되었습니다. 다시 시도해주세요.',
  SERVER_ERROR: '서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.',
  RATE_LIMIT_ERROR: '요청이 너무 많습니다. 잠시 후 다시 시도해주세요.',
  ACCESS_DENIED_ERROR: '접근 권한이 없습니다.',
  AUTH_EXPIRED_ERROR: '인증이 만료되었습니다. 다시 로그인해주세요.',
  UNKNOWN_ERROR: '알 수 없는 오류가 발생했습니다.',
  REGISTER_SUCCESS_MESSAGE: '회원가입이 완료되었습니다. 이메일을 확인해주세요.',
  VERIFICATION_RESENT_MESSAGE: '인증 이메일이 재전송되었습니다.',
  PASSWORD_RESET_SENT_MESSAGE: '비밀번호 재설정 이메일이 전송되었습니다.',
  PASSWORD_RESET_SUCCESS_MESSAGE: '비밀번호가 재설정되었습니다.',
  FAVORITE_REMOVED_MESSAGE: '즐겨찾기가 삭제되었습니다.',
  NO_ACCOUNT_TEXT: '계정이 없으신가요?',
  HAVE_ACCOUNT_TEXT: '이미 계정이 있으신가요?',
  FORGOT_PASSWORD_TEXT: '비밀번호를 잊으셨나요?',
  DIDNT_REQUEST_RESET_TEXT: '만약 비밀번호 재설정을 요청하지 않으셨다면, 이 이메일을 무시하세요.',
  TOKEN_VALID_FOR_24_HOURS: '이 링크는 24시간 동안 유효합니다.',
  TOKEN_VALID_FOR_1_HOUR: '이 링크는 1시간 동안 유효합니다.',
  MOVIE_APP_TITLE: '🎬 Movie Finder',
  MOVIE_TYPE_MOVIE: 'movie',
  POSTER_NOT_AVAILABLE: 'N/A',
  DEFAULT_POSTER: 'https://via.placeholder.com/300x445?text=No+Image',
  SESSION_STORAGE_SEARCH_KEY: 'searchQuery',
  LOCAL_STORAGE_TOKEN_KEY: 'accessToken',
  API_BASE_URL: (import.meta as any).env?.VITE_API_URL || 'http://localhost:3001',
  API_TIMEOUT: 10000,
  TOP_RATED_MOVIES_LIMIT: 12
} as const