export const UI_CONSTANTS = {
  SEARCH_DEBOUNCE_DELAY: 500,
  LOADING_TEXT: '読み込み中...',
  NO_RESULTS_TEXT: '検索結果がありません。',
  LOADING_TOP_RATED_TEXT: '高評価映画リストを読み込み中です...',
  SEARCH_PLACEHOLDER: '映画タイトルを入力してください...',
  HERO_TITLE: '今日見る映画を探しましょう',
  HERO_DESCRIPTION: 'タイトルで検索して好きな映画を見つけ、心に響く作品はハートでお気に入りに保存できます。',
  FAVORITES_TITLE: 'お気に入り',
  EMPTY_FAVORITES_TEXT: 'お気に入りの映画がありません。',
  LOGIN_TITLE: 'ログイン',
  REGISTER_TITLE: '会員登録',
  VERIFY_EMAIL_TITLE: 'メール認証',
  VERIFY_EMAIL_LOADING_TEXT: 'メールを認証中...',
  VERIFY_EMAIL_SUCCESS_TEXT: 'メール認証が完了しました！ ログインできます。',
  VERIFY_EMAIL_SUCCESS_BUTTON: 'ログインページへ移動',
  LOGOUT_BUTTON: 'ログアウト',
  FAVORITES_BUTTON: 'お気に入り',
  BACK_BUTTON: '戻る',
  SUBMIT_BUTTON: '送信',
  LOGIN_BUTTON: 'ログイン',
  REGISTER_BUTTON: '会員登録',
  RESEND_VERIFICATION_BUTTON: '認証メール再送信',
  FORGOT_PASSWORD_BUTTON: 'パスワードを忘れた',
  RESET_PASSWORD_BUTTON: 'パスワードリセット',
  EMAIL_LABEL: 'メール',
  PASSWORD_LABEL: 'パスワード',
  NAME_LABEL: '名前',
  CONFIRM_PASSWORD_LABEL: 'パスワード確認',
  TOKEN_LABEL: 'トークン',
  PLOT_LABEL: 'あらすじ',
  DIRECTOR_LABEL: '監督',
  ACTORS_LABEL: '出演',
  GENRE_LABEL: 'ジャンル',
  RATING_LABEL: '評価',
  NO_PLOT_TEXT: 'あらすじ情報がありません。',
  NO_INFO_TEXT: '情報なし',
  NO_RATING_TEXT: '評価なし',
  EMAIL_PLACEHOLDER: 'your@email.com',
  PASSWORD_PLACEHOLDER: '비밀번호를 입력하세요',
  NAME_PLACEHOLDER: '이름을 입력하세요',
  PASSWORD_MIN_LENGTH_PLACEHOLDER: '비밀번호를 입력하세요 (최소 6자)',
  EMAIL_ALREADY_EXISTS_ERROR: 'すでに登録されているメールです。',
  INVALID_CREDENTIALS_ERROR: 'メールまたはパスワードが正しくありません。',
  EMAIL_VERIFICATION_REQUIRED_ERROR: 'メール認証が必要です。',
  USER_NOT_FOUND_ERROR: 'ユーザーが見つかりません。',
  RESOURCE_NOT_FOUND_ERROR: 'リクエストされたリソースが見つかりません。',
  INVALID_TOKEN_ERROR: '無効な認証トークンです。',
  EXPIRED_TOKEN_ERROR: '無効または期限切れのトークンです。',
  ALREADY_VERIFIED_ERROR: 'すでに認証されたメールです。',
  MOVIE_NOT_FOUND_ERROR: '映画が見つかりません。',
  ALREADY_FAVORITED_ERROR: 'すでにブックマークに追加された映画です。',
  FAVORITE_NOT_FOUND_ERROR: 'ブックマークが見つかりません。',
  FAVORITE_PROCESS_ERROR: 'ブックマーク処理中にエラーが発生しました。',
  SEARCH_ERROR: '映画の読み込み中にエラーが発生しました。',
  NETWORK_ERROR: 'ネットワーク接続を確認してください。',
  TIMEOUT_ERROR: 'リクエスト時間が超過しました。再度お試しください。',
  SERVER_ERROR: 'サーバーエラーが発生しました。しばらくしてから再度お試しください。',
  RATE_LIMIT_ERROR: 'リクエストが多すぎます。しばらくしてから再度お試しください。',
  ACCESS_DENIED_ERROR: 'アクセス権限がありません。',
  AUTH_EXPIRED_ERROR: '認証が期限切れです。再度ログインしてください。',
  UNKNOWN_ERROR: '不明なエラーが発生しました。',
  REGISTER_SUCCESS_MESSAGE: '会員登録が完了しました。メールを確認してください。',
  VERIFICATION_RESENT_MESSAGE: '認証メールが再送信されました。',
  PASSWORD_RESET_SENT_MESSAGE: 'パスワードリセットメールが送信されました。',
  PASSWORD_RESET_SUCCESS_MESSAGE: 'パスワードがリセットされました。',
  FAVORITE_REMOVED_MESSAGE: 'ブックマークが削除されました。',
  NO_ACCOUNT_TEXT: 'アカウントをお持ちですか？',
  HAVE_ACCOUNT_TEXT: 'すでにアカウントをお持ちですか？',
  FORGOT_PASSWORD_TEXT: 'パスワードを忘れましたか？',
  DIDNT_REQUEST_RESET_TEXT: 'パスワードリセットをリクエストしていない場合は、このメールを無視してください。',
  TOKEN_VALID_FOR_24_HOURS: 'このリンクは24時間有効です。',
  TOKEN_VALID_FOR_1_HOUR: 'このリンクは1時間有効です。',
  MOVIE_APP_TITLE: '🎬 Movie Finder',
  MOVIE_TYPE_MOVIE: 'movie',
  POSTER_NOT_AVAILABLE: 'N/A',
  DEFAULT_POSTER: 'https://via.placeholder.com/300x445?text=No+Image',
  SESSION_STORAGE_SEARCH_KEY: 'searchQuery',
  LOCAL_STORAGE_TOKEN_KEY: 'accessToken',
  API_BASE_URL: (import.meta as any).env?.VITE_API_URL || 'http://localhost:3001',
  API_TIMEOUT: 10000,
  TOP_RATED_MOVIES_LIMIT: 12
} as const